package com.minecolonies.core.generation.defaults;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.minecolonies.api.util.constant.Constants;
import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.function.Function;

/**
 * Assembles the one language file the game actually loads, {@code assets/minecolonies/lang/en_us.json}.
 *
 * <h2>Why this exists at all</h2>
 * Upstream never had an {@code en_us.json} in the repository: {@code tools/export_lang/exportLang.py} pulls every
 * language, English included, out of POEditor and drops the result into {@code src/main/resources/assets/minecolonies/lang/}
 * as part of the release pipeline. Only {@code manual_en_us.json} — the strings that are not managed by POEditor —
 * is committed. On top of that, three more lang files are produced by datagen and are *not* merged into
 * {@code en_us.json} by anything in the repository either; upstream's POEditor export happens to contain their keys
 * as well, because they were uploaded there.
 * <p>
 * This port has no POEditor project, so nothing ever produced {@code en_us.json} and every string in the game
 * rendered as its raw key. The four files that *are* in the repository between them carry the full English text,
 * so the fix is to merge them:
 * <ul>
 *   <li>{@code lang/manual_en_us.json} — authored, in {@code src/main/resources} (2767 keys: GUI, chat, blocks,
 *       items, entities, config, advancements, …)</li>
 *   <li>{@code lang/default.json} — generated by {@code AbstractResearchProvider} (research names/subtitles)</li>
 *   <li>{@code lang/quests.json} — generated by {@link QuestTranslationProvider} (quest dialogue)</li>
 *   <li>{@code lang/tag.item.json} — generated by {@link DefaultItemTagsProvider} (item tag display names)</li>
 * </ul>
 * The four key sets are pairwise disjoint, so the merge is a plain union with no precedence to decide. A conflict
 * would mean a genuine authoring mistake, so one is logged loudly rather than silently resolved.
 *
 * <h2>Why a datagen provider and not a Gradle step</h2>
 * A Gradle task would have to hardcode which files to merge and where they land, and would run outside the
 * {@code HashCache} that owns {@code src/main/generated} — a subsequent {@code runDatagen} would then delete its
 * output as an untracked stale file. As a provider the merge is just another tracked output in the directory it
 * belongs to, it runs in the same JVM as the providers that produce its inputs, and — the part a Gradle task cannot
 * do at all — it can walk the live registries and report which registered block/item/entity has no translation.
 *
 * <h2>Ordering</h2>
 * {@link net.minecraft.data.DataGenerator.Cached#run} iterates {@code providersToRun} (a {@code LinkedHashMap}) in
 * insertion order and {@code join()}s each provider before starting the next, so the three generated inputs are on
 * disk by the time this runs — as long as it is registered *last* in
 * {@link com.minecolonies.core.generation.MineColoniesDataGenerator}. Keep it there.
 */
public class DefaultLanguageProvider implements DataProvider
{
    private static final Logger LOGGER = LoggerFactory.getLogger(DefaultLanguageProvider.class);

    /**
     * The authored file, read off the classpath ({@code src/main/resources}) rather than the datagen output folder:
     * nothing generates it.
     */
    private static final String MANUAL_RESOURCE = "/assets/" + Constants.MOD_ID + "/lang/manual_en_us.json";

    /**
     * The generated files, read back out of the datagen output folder — i.e. this run's output, not whatever a
     * previous run happened to leave on the classpath.
     */
    private static final List<String> GENERATED_INPUTS = List.of("default", "quests", "tag.item");

    private final PackOutput.PathProvider langPath;

    public DefaultLanguageProvider(@NotNull final FabricPackOutput output)
    {
        this.langPath = output.createPathProvider(PackOutput.Target.RESOURCE_PACK, "lang");
    }

    @NotNull
    @Override
    public String getName()
    {
        return "MineColonies Language";
    }

    @NotNull
    @Override
    public CompletableFuture<?> run(@NotNull final CachedOutput cache)
    {
        final Map<String, JsonElement> merged = new LinkedHashMap<>();

        readManual(merged);
        for (final String name : GENERATED_INPUTS)
        {
            readGenerated(merged, name);
        }

        auditRegistries(merged);

        final JsonObject json = new JsonObject();
        merged.forEach(json::add);
        // saveStable sorts the keys, so the file is stable regardless of the order the inputs were read in.
        return DataProvider.saveStable(cache, json, langPath.json(Identifier.fromNamespaceAndPath(Constants.MOD_ID, "en_us")));
    }

    private void readManual(@NotNull final Map<String, JsonElement> merged)
    {
        try (final InputStream in = DefaultLanguageProvider.class.getResourceAsStream(MANUAL_RESOURCE))
        {
            if (in == null)
            {
                throw new IllegalStateException(MANUAL_RESOURCE + " is not on the datagen classpath");
            }
            try (final Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8))
            {
                absorb(merged, JsonParser.parseReader(reader).getAsJsonObject(), MANUAL_RESOURCE);
            }
        }
        catch (final IOException e)
        {
            throw new IllegalStateException("Could not read " + MANUAL_RESOURCE, e);
        }
    }

    private void readGenerated(@NotNull final Map<String, JsonElement> merged, @NotNull final String name)
    {
        final Path path = langPath.json(Identifier.fromNamespaceAndPath(Constants.MOD_ID, name));
        if (!Files.isRegularFile(path))
        {
            // Not fatal on its own, but it means a provider that should have run before this one did not.
            LOGGER.error("Language input {} is missing -- is {} still registered last in MineColoniesDataGenerator?",
              path, DefaultLanguageProvider.class.getSimpleName());
            return;
        }

        try (final Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8))
        {
            absorb(merged, JsonParser.parseReader(reader).getAsJsonObject(), path.toString());
        }
        catch (final IOException e)
        {
            throw new IllegalStateException("Could not read " + path, e);
        }
    }

    private void absorb(@NotNull final Map<String, JsonElement> merged,
                        @NotNull final JsonObject source,
                        @NotNull final String origin)
    {
        for (final Map.Entry<String, JsonElement> entry : source.entrySet())
        {
            final JsonElement previous = merged.put(entry.getKey(), entry.getValue());
            if (previous != null && !previous.equals(entry.getValue()))
            {
                LOGGER.warn("Translation key {} is defined twice with different text; {} wins", entry.getKey(), origin);
            }
        }
    }

    /**
     * Walks the registries this mod contributes to and reports anything whose translation key the merged file does
     * not cover. Purely informational — a missing string is not worth failing a build over, but it is exactly the
     * class of bug ("the block shows its key in the creative menu") that is otherwise only found by playing.
     */
    private void auditRegistries(@NotNull final Map<String, JsonElement> merged)
    {
        final List<String> missing = new ArrayList<>();

        collectMissing(missing, merged, BuiltInRegistries.BLOCK, "block", b -> b.getDescriptionId());
        collectMissing(missing, merged, BuiltInRegistries.ITEM, "item", i -> i.getDescriptionId());
        collectMissing(missing, merged, BuiltInRegistries.ENTITY_TYPE, "entity", e -> e.getDescriptionId());

        if (missing.isEmpty())
        {
            LOGGER.info("Language: {} keys, every registered block/item/entity is translated", merged.size());
        }
        else
        {
            LOGGER.warn("Language: {} keys, but {} registry entries have no translation:", merged.size(), missing.size());
            missing.forEach(key -> LOGGER.warn("  untranslated: {}", key));
        }
    }

    private <T> void collectMissing(@NotNull final List<String> missing,
                                    @NotNull final Map<String, JsonElement> merged,
                                    @NotNull final Registry<T> registry,
                                    @NotNull final String what,
                                    @NotNull final Function<T, String> descriptionId)
    {
        for (final Map.Entry<net.minecraft.resources.ResourceKey<T>, T> entry : registry.entrySet())
        {
            if (!entry.getKey().identifier().getNamespace().equals(Constants.MOD_ID))
            {
                continue;
            }
            final String key = descriptionId.apply(entry.getValue());
            if (!merged.containsKey(key))
            {
                missing.add(what + " " + entry.getKey().identifier() + " -> " + key);
            }
        }
    }
}
