package com.minecolonies.api.entity.mobs.drownedpirate;

import com.minecolonies.api.MinecoloniesAPIProxy;
import com.minecolonies.api.entity.mobs.AbstractEntityMinecoloniesMonster;
import com.minecolonies.api.entity.mobs.RaiderType;
import com.minecolonies.api.entity.pathfinding.registry.IPathNavigateRegistry;
import com.minecolonies.core.entity.pathfinding.navigation.AbstractAdvancedPathNavigate;
import com.minecolonies.core.entity.pathfinding.navigation.PathingStuckHandler;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelReader;
import org.jetbrains.annotations.NotNull;

import static com.minecolonies.core.colony.events.raid.RaiderConstants.*;
import static com.minecolonies.core.colony.events.raid.RaiderConstants.ATTACK_DAMAGE;

/**
 * Abstract for all drowned pirate entities.
 * <p>
 * Breathing under water is not handled here. All six drowned pirate types are in the vanilla
 * {@code minecraft:can_breathe_under_water} entity type tag (generated by {@code DefaultEntityTypeTagsProvider}),
 * which is the switch {@code LivingEntity#canBreatheUnderwater} reads and the one that stops the air supply from
 * being decreased in the first place -- rather than overriding {@code decreaseAirSupply} to return its argument,
 * which only silenced the counter and left every other test of that tag answering "no".
 */
public abstract class AbstractDrownedEntityPirate extends AbstractEntityMinecoloniesMonster
{
    /**
     * Swim speed for pirates
     */
    private static final double PIRATE_SWIM_BONUS = 3.0;

    /**
     * Amount of unique pirate textures.
     */
    private static final int PIRATE_TEXTURES = 4;

    /**
     * Constructor method for Abstract Barbarians.
     *
     * @param type  the type.
     * @param world the world.
     */
    public AbstractDrownedEntityPirate(final EntityType<? extends AbstractDrownedEntityPirate> type, final Level world)
    {
        super(type, world, PIRATE_TEXTURES);
        initStatsFor(BARBARIAN_BASE_HEALTH * (world.getDifficulty().getId() + 0.1), world.getDifficulty().getId() + 0.1, ATTACK_DAMAGE * world.getDifficulty().getId());
    }

    @Override
    public void playAmbientSound()
    {
        if (level().getRandom().nextInt(OUT_OF_ONE_HUNDRED) <= ONE)
        {
            this.playSound(this.isInWater() ? SoundEvents.DROWNED_AMBIENT_WATER : SoundEvents.DROWNED_AMBIENT, this.getSoundVolume(), this.getVoicePitch());
        }
    }

    @Override
    public boolean checkSpawnObstruction(final LevelReader level)
    {
        return level.isUnobstructed(this);
    }

    @NotNull
    @Override
    public AbstractAdvancedPathNavigate getNavigation()
    {
        if (this.newNavigator == null)
        {
            this.newNavigator = IPathNavigateRegistry.getInstance().getNavigateFor(this);
            this.navigation = newNavigator;
            newNavigator.setSwimSpeedFactor(getSwimSpeedFactor());
            newNavigator.setSpeedModifier(0.5);
            newNavigator.getPathingOptions().withStartSwimCost(0.0D).withSwimCost(0.0D).withDivingCost(0.0D).withCanEnterDoors(true).withCanEnterGates(true).withDropCost(0.0D).withJumpCost(0.0D).withWalkUnderWater(true).withNonLadderClimbableCost(0.0D).setPassDanger(true);
            PathingStuckHandler stuckHandler = PathingStuckHandler.createStuckHandler()
                                                 .withTakeDamageOnStuck(0.4f)
                                                 .withBuildLeafBridges()
                                                 .withChanceToByPassMovingAway(0.20)
                                                 .withPlaceLadders();

            if (MinecoloniesAPIProxy.getInstance().getConfig().getServer().raidersbreakblocks.get())
            {
                stuckHandler.withBlockBreaks();
                stuckHandler.withCompleteStuckBlockBreak(6);
            }

            newNavigator.setStuckHandler(stuckHandler);
            this.newNavigator.setCanFloat(true);
        }
        return newNavigator;
    }

    @Override
    public RaiderType getRaiderType()
    {
        return RaiderType.PIRATE;
    }

    @Override
    public double getSwimSpeedFactor()
    {
        return PIRATE_SWIM_BONUS;
    }
}
