// Date: 5/28/2016 10:20:40 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.minecolonies.core.client.model;

import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.util.Unit;
import net.minecraft.client.model.Model;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
import net.minecraft.client.model.HumanoidModel;

public class ScarecrowModel extends Model<Unit>
{
    //fields
    ModelPart head;
    ModelPart post;
    ModelPart leftArmPeg;
    ModelPart rightArmPeg;
    ModelPart torso;
    ModelPart rightLegPeg;
    ModelPart leftLegPeg;
    ModelPart leftArm;
    ModelPart rightArm;
    ModelPart rightLeg;
    ModelPart leftLeg;

    public ScarecrowModel(final ModelPart part)
    {
        super(part, RenderTypes::entitySolid);
        head = part.getChild("head");
        post = part.getChild("post");
        leftArmPeg = part.getChild("leftArmPeg");
        rightArmPeg = part.getChild("rightArmPeg");
        torso = part.getChild("torso");
        rightLegPeg = part.getChild("rightLegPeg");
        leftLegPeg = part.getChild("leftLegPeg");
        leftArm = part.getChild("left_arm");
        rightArm = part.getChild("right_arm");
        rightLeg = part.getChild("right_leg");
        leftLeg = part.getChild("left_leg");
    }

    /**
     * Builds the scarecrow mesh.
     * <p>
     * PORT-NOTE(26.2): this used to start from {@link HumanoidModel#createMesh} and overwrite the humanoid parts it
     * cared about, relying on an overridden {@code renderToBuffer} to draw only the eleven parts named below. In 26.2
     * {@code Model#renderToBuffer} is {@code final} and always draws the whole baked root, so the two humanoid parts
     * the scarecrow never overwrote — {@code body} on the root, and {@code hat}, which
     * {@link PartDefinition#addOrReplaceChild} carries over onto the replacing {@code head} — started being drawn as
     * well. {@code hat} is a 9x9x9 cube that lands half-sunk in the ground beside the scarecrow's base; because the
     * sheet is a 64x32 skin layout padded out to 128x64 and its unused skin gaps are stored as opaque-white
     * {@code (255,255,255,0)} texels, and because {@code entitySolid} ignores alpha, most of its faces draw as solid
     * white slabs. The scarecrow declares every part it needs, so the mesh starts empty and the humanoid leftovers
     * simply never exist.
     *
     * @return the layer definition, against the 128x64 sheet the textures actually are.
     */
    public static LayerDefinition createMesh()
    {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partDefinition = meshdefinition.getRoot();

        PartDefinition headDefinition = partDefinition.addOrReplaceChild("head",
          CubeListBuilder.create().texOffs(0, 0).texOffs(0, 0).addBox(-8.2F, -35.6F, -4.2F, 8, 8, 8).mirror()
          , PartPose.offsetAndRotation(7F, 24F, -1F, 0F, 0.1858931F, -0.1092638F));

        PartDefinition postDefinition = partDefinition.addOrReplaceChild("post",
          CubeListBuilder.create().texOffs(0, 32).addBox(-1F, -16F, -1F, 2, 16, 2).mirror()
          , PartPose.offset(0F, 24F, 0F));

        PartDefinition leftArmPegDefinition = partDefinition.addOrReplaceChild("leftArmPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(23.5F, 1F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F,  0F, 0F, -1.351339F));

        PartDefinition rightArmPegDefinition = partDefinition.addOrReplaceChild("rightArmPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(-28F, 15.8F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F,  0F, 0F, 1.351339F));

        PartDefinition torsoDefinition = partDefinition.addOrReplaceChild("torso",
          CubeListBuilder.create().texOffs(16, 16).addBox(-10.3F, -27.6F, -2F, 8, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -0.0349066F));

        PartDefinition rightLegPegDefinition = partDefinition.addOrReplaceChild("rightLegPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(-11F, -4F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, 0.0872665F));

        PartDefinition leftLegPegDefinition = partDefinition.addOrReplaceChild("leftLegPeg",
          CubeListBuilder.create().texOffs(9, 33).addBox(-4.5F, -5F, -1F, 2, 2, 2).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -0.0872665F));

        PartDefinition leftArmDefinition = partDefinition.addOrReplaceChild("left_arm",
          CubeListBuilder.create().texOffs(40, 16).addBox(22.5F, -10F, -1.99F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -1.351339F));

        PartDefinition rightArmDefinition = partDefinition.addOrReplaceChild("right_arm",
          CubeListBuilder.create().texOffs(40, 16).addBox(-29F, 4.8F, -1.99F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, 1.351339F));

        PartDefinition rightLegDefinition = partDefinition.addOrReplaceChild("right_leg",
          CubeListBuilder.create().texOffs(0, 16).addBox(-12F, -15F, -1.99F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, 0.0872665F));

        PartDefinition leftLegDefinition = partDefinition.addOrReplaceChild("left_leg",
          CubeListBuilder.create().texOffs(0, 16).addBox(-5.5F, -16F, -1.98F, 4, 12, 4).mirror()
          , PartPose.offsetAndRotation(7F, 24F, 0F, 0F, 0F, -0.0872665F));

        return LayerDefinition.create(meshdefinition,  128,  64 );
    }

}
